### ISSUE TITLE
JSON Decode - Pool JSONToken

### ISSUE THREAD

**Issue by stickupkid** [mikechambers/as3corelib#141]
Polling calls to JSONDecode makes a lot of JSONTokens, ideally a pool should be setup so that it can reuse tokens it creates. Creating lots of tokens at runtime and then letting them be GC'd (if and when) can cause performance issues in performance critical devices (mobiles and the like). A solution to this would be to create a Pool of some description that takes the Tokens and creates them once and reuses them.

If the pool is large enough just create more objects in the pool to be reused.

**Comment by darronschall** [comment]
Fixed in commit 064139a0ce1e0422bb6e23a03614157bc8d00edb
