### ISSUE TITLE
JSON.decode object not in order

### ISSUE THREAD

**Issue by shrimpwagon** [mikechambers/as3corelib#143]
# Recreation
1. Use a JSON object that has their labels in some sort of order.
2. Create an object and assign it JSON.decode(json)
3. Using a for loop, iterate through each label and trace
# Expectations

I thought it would just trace it in order of appearance in the JSON object but it seems to be random. It is even different from run to run.
# Environment

Windows XP SP3 - Adobe CS3 Flash 9 - as3corelib-.93
# Example

In this example, the object "presets" has its labels in some sort of order. This is particularly dealing with the size of signs. I would think the trace would be like; 2x8, 2x12, 3x6 ... etc.
## JSON:

{"status": "success","presets": {"2x8": "2 in. x 8 in.","2x12": "2 in. x 1 ft.","3x6": "3 in. x 6 in.","3x10": "3 in. x 10 in.","3x12": "3 in. x 1 ft.","4x4": "4 in. x 4 in.","4x8": "4 in. x 8 in.","4x12": "4 in. x 1 ft.","4x24": "4 in. x 2 ft.","6x6": "6 in. x 6 in.","6x8": "6 in. x 8 in.","6x12": "6 in. x 1 ft.","6x18": "6 in. x 18 in.","6x24": "6 in. x 2 ft.","12x18": "1 ft. x 18 in.","12x24": "1 ft. x 2 ft.","12x30": "1 ft. x 30 in.","12x36": "1 ft. x 3 ft.","12x48": "1 ft. x 4 ft.","12x60": "1 ft. x 5 ft.","12x72": "1 ft. x 6 ft.","12x96": "1 ft. x 8 ft.","12x120": "1 ft. x 10 ft.","18x24": "18 in. x 24 in.","18x30": "18 in. x 30 in.","18x36": "18 in. x 3 ft.","18x48": "18 in. x 4 ft.","18x60": "18 in. x 5 ft.","18x72": "18 in. x 6 ft.","18x96": "18 in. x 8 ft.","18x120": "18 in. x 10 ft.","20x28": "20 in. x 28 in.","22x28": "22 in. x 28 in.","24x24": "2 ft. x 2 ft.","24x30": "2 ft. x 30 in.","24x36": "2 ft. x 3 ft.","24x48": "2 ft. x 4 ft.","24x72": "2 ft. x 6 ft.","24x96": "2 ft. x 8 ft.","24x120": "2 ft. x 10 ft.","36x36": "3 ft. x 3 ft.","36x48": "3 ft. x 4 ft.","36x60": "3 ft. x 5 ft.","36x72": "3 ft. x 6 ft.","36x96": "3 ft. x 8 ft.","36x120": "3 ft. x 10 ft.","36x144": "3 ft. x 12 ft.","36x168": "3 ft. x 14 ft.","36x192": "3 ft. x 16 ft.","48x48": "4 ft. x 4 ft.","48x60": "4 ft. x 5 ft.","48x72": "4 ft. x 6 ft.","48x96": "4 ft. x 8 ft.","48x120": "4 ft. x 10 ft.","48x144": "4 ft. x 12 ft.","48x168": "4 ft. x 14 ft.","48x192": "4 ft. x 16 ft.","60x60": "5 ft. x 5 ft.","60x72": "5 ft. x 6 ft.","60x96": "5 ft. x 8 ft.","60x120": "5 ft. x 10 ft.","60x144": "5 ft. x 12 ft.","60x168": "5 ft. x 14 ft.","60x192": "5 ft. x 16 ft.","72x72": "6 ft. x 6 ft.","72x96": "6 ft. x 8 ft.","72x120": "6 ft. x 10 ft.","72x144": "6 ft. x 12 ft.","72x168": "6 ft. x 14 ft.","72x192": "6 ft. x 16 ft.","96x96": "8 ft. x 8 ft.","96x120": "8 ft. x 10 ft.","96x144": "8 ft. x 12 ft.","96x168": "8 ft. x 14 ft.","96x192": "8 ft. x 16 ft.","96x240": "8 ft. x 20 ft."},"request": {"sign_code": "CA","thickness": "0.125","color": "1","side": "2"}}
## Code:

```
this._sign_presets = (JSON.decode(json_strong)).presets; 
for (var sign_preset in this._sign_presets) {
    trace(sign_preset);
}
```
## Trace:

8x72
60x72
18x120
12x30
36x168
12x48
48x168
72x144
60x96
24x120
36x36
48x60
60x144
12x96
96x192
96x96
36x192
12x120
12x60
48x48
24x96
24x72
48x72
4x24
3x10
2x8
36x144
96x168
18x30
18x60
12x24
4x8
36x72
24x24
72x96
22x28
4x12
2x12
24x36
72x192
48x144
60x192
72x168
60x60
48x192
36x120
6x6
72x120
96x120
3x12
96x144
60x168
36x48
4x4
12x72
60x120
96x240
6x18
20x28
72x72
36x60
3x6
6x24
36x96
48x120
6x12
12x18
24x48
18x48
12x36
18x24
18x36
24x30
6x8
18x96
48x96

**Comment by shrimpwagon** [comment]
Anything?

**Comment by darronschall** [comment]
This isn't a bug in the JSON decoder.  The behavior you are seeing stems from the use of a "for..in" loop to iterate over properties of an object.  Objects in AS3 are not "ordered".

The better way to encode this information would be to use an array [] instead of an object {}:

**Comment by shrimpwagon** [comment]
Sweet, that will work. Thank you so much.
