### ISSUE TITLE
[Bug] JPGEncoder.encode problem with loaded image's bitmap data

### ISSUE THREAD

**Issue by angelhdzmultimedia** [mikechambers/as3corelib#196]
I don't know if this repository is active, but here I go.

I tried many versions of JPGEncoder library, also tried on AIR 28.0 and 31.0 SKDs.

Then I use .encode() on an empty BitmapData, it works OK. But when I use it on a bitmap data created from a loaded image, compiler crashes. I used a try/catch. No errors shown.

Is this library working or should I find another one?

Thanks!

**Comment by nida624** [comment]
288113882

**Comment by nida624** [comment]
288113882__
